shark-docker/
├── docker-compose.yml
└── nodeapp/
    ├── Dockerfile
    ├── package.json
    ├── app.js
    ├── db.js
    ├── models/
    │   └── sharks.js
    ├── routes/
    │   └── sharks.js
    └── views/
        ├── index.ejs
        └── TyrellEnglish
